### ISSUE TITLE
Hue Natural light scene

### ISSUE THREAD

**Issue by lukvac** [chadwpalm/Lumunarr#23]
Hi, can you add support for Philips Hue natural light scene please ? It´s not visible in the list of scenes at this moment.

![image](https://github.com/chadwpalm/Lumunarr/assets/135635608/4ba0d27c-4ad3-415a-97f4-39c10c5a833d)

**Comment by chadwpalm** [comment]
Smart scenes are part of the Hue v2 API which I was intending to update Lumunarr to start using after the new year. Looks like I'll be getting started on that!

Hopefully it won't take too long to do. I will include Smart Scenes into that update.

Chad

**Comment by lukvac** [comment]
Thank you very much for this information. Great app by the way, I'm using
it every day and you did really good work here.


Dne po 22. 1. 2024 21:24 uživatel Chad ***@***.***> napsal:

**Comment by chadwpalm** [comment]
@lukvac 

I've made good progress with the update to Hue API v2 and the Hue Natural Light scene has been incorporated in and working nicely.

Due to differences in the Hue API's, things like light/scene/group IDs have been changed, so I need to work on code that will update and backup the config file as this will be a breaking change to older versions. I want to make sure I get it right.

I'm hoping to get a release to the developer channel sometime this week. Thanks for your patience!

Chad

**Comment by lukvac** [comment]
Hi,

I have quickly tested it and natural scene working well. But global scene
transition time doesn’t work in this release.

S pozdravem,

Lukáš Vacula


po 19. 2. 2024 v 4:43 odesílatel Chad ***@***.***> napsal:

**Comment by lukvac** [comment]
Yes, it was this one.

S pozdravem,

Lukáš Vacula


čt 22. 2. 2024 v 20:20 odesílatel Chad ***@***.***> napsal:

**Comment by chadwpalm** [comment]
@lukvac I see the problem in the code. I'm assuming this is happening when the scene is set to turn the lights off? I'll fix it before release to develop channel. Thanks for pointing it out!

**Comment by chadwpalm** [comment]
@lukvac I've fixed the global transition issue in tag "feature-hue-api-v2-1.4.0.74". Let me know if it is working properly now.

Be aware that smart scenes (like Natural Light) do not support on/off transition times. This is an issue with Hue's API. Nothing I can do about that.

**Comment by lukvac** [comment]
All is now working very well for me. Transition time is important for me
mainly from on to off and for this state it´s working well also with smart
scene.

Thanks a lot.

S pozdravem,

Lukáš Vacula


pá 23. 2. 2024 v 5:43 odesílatel Chad ***@***.***> napsal:
