### ISSUE TITLE
Editing an existing client setting is not populating Action Scene

### ISSUE THREAD

**Issue by wajaRick** [chadwpalm/Lumunarr#27]
After creating a new client setting, I wanted to go back and make some changes. 
I selected edit for the client.
Play, Stop, Pause, Resume, Scrobble only have Select <Play, Stop, Pause, Resume. Scrobble> Action Scene, None, or Off.
None of the Action Scenes are loaded from the Bridge.
Version 1.4.0

**Comment by chadwpalm** [comment]
Do you see the scenes when you create a new Client profile? Is it just when you edit? If you look at the config file does it look like the scene IDs are there after you save it? Do the Docker logs show anything unusual?

**Comment by wajaRick** [comment]
Scenes are displayed when creating a new Client profile.
Only an issue for edit.
This looks correct in settings.js:
            "play": "Off",
            "stop": "6afb752c-d8af-45c5-84e7-8ba784ba2c4d",
            "pause": "0d5cb8b0-c9e4-49ee-8956-ddcf6c8ee353",
            "resume": "Off",
            "scrobble": "0d5cb8b0-c9e4-49ee-8956-ddcf6c8ee353",
Nothing unusual in Docker logs
[2024-03-27 08:09:06] [INFO]  Retrieving Rooms
[2024-03-27 08:09:06] [INFO]  Retrieving Zones
[2024-03-27 08:09:06] [INFO]  Retrieving Light Scenes
[2024-03-27 08:09:06] [INFO]  Retrieving Smart Scenes
[2024-03-27 08:09:06] [INFO]  Retrieving Plex Accounts
[2024-03-27 08:09:07] [INFO]  Retrieving Server Admin Information
[2024-03-27 08:09:08] [INFO]  Retrieving Plex Clients
For an edit test, I changed the Scene Transition Time.
I verified this is saved and the above settings were not changed.
Tested on my client and it works as expected.

**Comment by chadwpalm** [comment]
The scenes might be loading from the bridge, but not populating in the fields. The scenes will not populate if a Room isn't selected. When you edit a client is the Room being populated from your settings file? Does the settings file show a room?

Ex.
...
&ensp;&ensp;"media": "movie",
&ensp;&ensp;"room": "Living Room",
&ensp;&ensp;"play": "6280a6aa-04b8-4f93-a7ed-d091e34c0878",
&ensp;&ensp;"stop": "b7b52a1e-3b0a-46da-bed1-8ed06c036f4a",
&ensp;&ensp;"pause": "b7b52a1e-3b0a-46da-bed1-8ed06c036f4a",
&ensp;&ensp;"resume": "6280a6aa-04b8-4f93-a7ed-d091e34c0878",
&ensp;&ensp;"scrobble": "da88958b-700b-4d74-8c9c-ff99d304ac7c",
&ensp;&ensp;"scrobbleDelayMs": "3000",
...

**Comment by wajaRick** [comment]
![image](https://github.com/chadwpalm/Lumunarr/assets/105322721/2053ba4a-d22c-4e07-b803-c0756d4f30df)
Room is in the settings file and being populated in the GUI.

**Comment by wajaRick** [comment]
Some more and hopefully helpful information.
If I select a different room and then go back to the Theater room, The actions are filled in for the Theater and the drop down now contains all the scenes available for the room.

**Comment by chadwpalm** [comment]
> Some more and hopefully helpful information. If I select a different room and then go back to the Theater room, The actions are filled in for the Theater and the drop down now contains all the scenes available for the room.

Okay, so that proves it is getting the scenes from the bridge, but it makes no sense why they are not populating. It pulls all of the scenes from the bridge then matches them to what are in the settings file.

The only immediate thing I can think to try if you haven't already tried this is to backup your settings file then delete it, then restart the container so it recreates a new settings file, then set it up again and test if you have the same problem.  Perhaps something got messed up in the settings file?

If after you do that you want to send me a dump of the logs from the time it restarted to when you have the issue, you can email them to me along with the settings file if you're comfortable doing that, that way you aren't posting them here publicly. chadwpalm@gmail.com

**Comment by wajaRick** [comment]
There is an error detected:
          if (this.props.isEdit) {
            var room = json[2].find(({ Id }) => Id === this.state.playScene).Room;
            if (this.state.room === undefined) this.setState({ room: room });
          }
Create.jsx:115 Uncaught TypeError: Cannot read properties of undefined (reading 'Room')
    at XMLHttpRequest.<anonymous> (Create.jsx:115:76)

I am using the Quad-Core Intel Celeron N5105 processor. Asustor-NAS FS6712X.

**Comment by chadwpalm** [comment]
Your last message helped me pinpoint the issue. Some code I had originally wrote to fill in the Room name if it was undefined was trying to pull the room information from the Play scene, but if the Play scenes was set to Off or None, there is no room to pull from.

I corrected the code and issued a hotfix to 1.4.1 build 78 to a test tag. Could you pull chadwpalm/lumunarr:Fix_No_Scene_Populate-1.4.1.78 and start up a container from that image and see if that fixes the problem? If it does, I will go ahead an propagate the fix into the Main and Develop tags.

Thanks,
Chad
